//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetStudio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool displayAll {
            get {
                return ((bool)(this["displayAll"]));
            }
            set {
                this["displayAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enablePreview {
            get {
                return ((bool)(this["enablePreview"]));
            }
            set {
                this["enablePreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool displayInfo {
            get {
                return ((bool)(this["displayInfo"]));
            }
            set {
                this["displayInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool openAfterExport {
            get {
                return ((bool)(this["openAfterExport"]));
            }
            set {
                this["openAfterExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int assetGroupOption {
            get {
                return ((int)(this["assetGroupOption"]));
            }
            set {
                this["assetGroupOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool convertTexture {
            get {
                return ((bool)(this["convertTexture"]));
            }
            set {
                this["convertTexture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool convertAudio {
            get {
                return ((bool)(this["convertAudio"]));
            }
            set {
                this["convertAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int convertType {
            get {
                return ((int)(this["convertType"]));
            }
            set {
                this["convertType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool eulerFilter {
            get {
                return ((bool)(this["eulerFilter"]));
            }
            set {
                this["eulerFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public decimal filterPrecision {
            get {
                return ((decimal)(this["filterPrecision"]));
            }
            set {
                this["filterPrecision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool exportAllNodes {
            get {
                return ((bool)(this["exportAllNodes"]));
            }
            set {
                this["exportAllNodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool exportSkins {
            get {
                return ((bool)(this["exportSkins"]));
            }
            set {
                this["exportSkins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exportAnimations {
            get {
                return ((bool)(this["exportAnimations"]));
            }
            set {
                this["exportAnimations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool collectAnimations {
            get {
                return ((bool)(this["collectAnimations"]));
            }
            set {
                this["collectAnimations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal boneSize {
            get {
                return ((decimal)(this["boneSize"]));
            }
            set {
                this["boneSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int fbxVersion {
            get {
                return ((int)(this["fbxVersion"]));
            }
            set {
                this["fbxVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int fbxFormat {
            get {
                return ((int)(this["fbxFormat"]));
            }
            set {
                this["fbxFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal scaleFactor {
            get {
                return ((decimal)(this["scaleFactor"]));
            }
            set {
                this["scaleFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool exportBlendShape {
            get {
                return ((bool)(this["exportBlendShape"]));
            }
            set {
                this["exportBlendShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool castToBone {
            get {
                return ((bool)(this["castToBone"]));
            }
            set {
                this["castToBone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool restoreExtensionName {
            get {
                return ((bool)(this["restoreExtensionName"]));
            }
            set {
                this["restoreExtensionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool encrypted {
            get {
                return ((bool)(this["encrypted"]));
            }
            set {
                this["encrypted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("147")]
        public byte key {
            get {
                return ((byte)(this["key"]));
            }
            set {
                this["key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enableConsole {
            get {
                return ((bool)(this["enableConsole"]));
            }
            set {
                this["enableConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int selectedGame {
            get {
                return ((int)(this["selectedGame"]));
            }
            set {
                this["selectedGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int selectedUnityCNKey {
            get {
                return ((int)(this["selectedUnityCNKey"]));
            }
            set {
                this["selectedUnityCNKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enableResolveDependencies {
            get {
                return ((bool)(this["enableResolveDependencies"]));
            }
            set {
                this["enableResolveDependencies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int selectedAssetMapType {
            get {
                return ((int)(this["selectedAssetMapType"]));
            }
            set {
                this["selectedAssetMapType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string selectedCABMapName {
            get {
                return ((string)(this["selectedCABMapName"]));
            }
            set {
                this["selectedCABMapName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skipContainer {
            get {
                return ((bool)(this["skipContainer"]));
            }
            set {
                this["skipContainer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool minimalAssetMap {
            get {
                return ((bool)(this["minimalAssetMap"]));
            }
            set {
                this["minimalAssetMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool modelsOnly {
            get {
                return ((bool)(this["modelsOnly"]));
            }
            set {
                this["modelsOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enableModelPreview {
            get {
                return ((bool)(this["enableModelPreview"]));
            }
            set {
                this["enableModelPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableFileLogging {
            get {
                return ((bool)(this["enableFileLogging"]));
            }
            set {
                this["enableFileLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableVerbose {
            get {
                return ((bool)(this["enableVerbose"]));
            }
            set {
                this["enableVerbose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"Animation\": {\r\n        \"Item1\": true,\r\n        \"Item2\": false\r\n    },\r\n  " +
            "  \"AnimationClip\": {\r\n        \"Item1\": true,\r\n        \"Item2\": true\r\n    },\r\n   " +
            " \"Animator\": {\r\n        \"Item1\": true,\r\n        \"Item2\": true\r\n    },\r\n    \"Anim" +
            "atorController\": {\r\n        \"Item1\": true,\r\n        \"Item2\": false\r\n    },\r\n    " +
            "\"AnimatorOverrideController\": {\r\n        \"Item1\": true,\r\n        \"Item2\": false\r" +
            "\n    },\r\n    \"AssetBundle\": {\r\n        \"Item1\": true,\r\n        \"Item2\": false\r\n " +
            "   },\r\n    \"AudioClip\": {\r\n        \"Item1\": true,\r\n        \"Item2\": true\r\n    }," +
            "\r\n    \"Avatar\": {\r\n        \"Item1\": true,\r\n        \"Item2\": false\r\n    },\r\n    \"" +
            "Font\": {\r\n        \"Item1\": true,\r\n        \"Item2\": true\r\n    },\r\n    \"GameObject" +
            "\": {\r\n        \"Item1\": true,\r\n        \"Item2\": false\r\n    },\r\n    \"IndexObject\":" +
            " {\r\n        \"Item1\": true,\r\n        \"Item2\": false\r\n    },\r\n    \"Material\": {\r\n " +
            "       \"Item1\": true,\r\n        \"Item2\": true\r\n    },\r\n    \"Mesh\": {\r\n        \"It" +
            "em1\": true,\r\n        \"Item2\": true\r\n    },\r\n    \"MeshFilter\": {\r\n        \"Item1\"" +
            ": true,\r\n        \"Item2\": false\r\n    },\r\n    \"MeshRenderer\": {\r\n        \"Item1\":" +
            " true,\r\n        \"Item2\": false\r\n    },\r\n    \"MiHoYoBinData\": {\r\n        \"Item1\":" +
            " true,\r\n        \"Item2\": true\r\n    },\r\n    \"MonoBehaviour\": {\r\n        \"Item1\": " +
            "true,\r\n        \"Item2\": true\r\n    },\r\n    \"MonoScript\": {\r\n        \"Item1\": true" +
            ",\r\n        \"Item2\": false\r\n    },\r\n    \"MovieTexture\": {\r\n        \"Item1\": true," +
            "\r\n        \"Item2\": false\r\n    },\r\n    \"PlayerSettings\": {\r\n        \"Item1\": true" +
            ",\r\n        \"Item2\": false\r\n    },\r\n    \"RectTransform\": {\r\n        \"Item1\": true" +
            ",\r\n        \"Item2\": false\r\n    },\r\n    \"Shader\": {\r\n        \"Item1\": true,\r\n    " +
            "    \"Item2\": true\r\n    },\r\n    \"SkinnedMeshRenderer\": {\r\n        \"Item1\": true,\r" +
            "\n        \"Item2\": false\r\n    },\r\n    \"Sprite\": {\r\n        \"Item1\": true,\r\n      " +
            "  \"Item2\": true\r\n    },\r\n    \"SpriteAtlas\": {\r\n        \"Item1\": true,\r\n        \"" +
            "Item2\": false\r\n    },\r\n    \"TextAsset\": {\r\n        \"Item1\": true,\r\n        \"Item" +
            "2\": true\r\n    },\r\n    \"Texture2D\": {\r\n        \"Item1\": true,\r\n        \"Item2\": t" +
            "rue\r\n    },\r\n    \"Transform\": {\r\n        \"Item1\": true,\r\n        \"Item2\": false\r" +
            "\n    },\r\n    \"VideoClip\": {\r\n        \"Item1\": true,\r\n        \"Item2\": true\r\n    " +
            "},\r\n    \"ResourceManager\": {\r\n        \"Item1\": true,\r\n        \"Item2\": false\r\n  " +
            "  }\r\n}")]
        public string types {
            get {
                return ((string)(this["types"]));
            }
            set {
                this["types"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\r\n        \"Name\": \"PGR GLB/KR\",\r\n        \"Key\": \"6B75726F6B75726F6B75726F6B7572" +
            "6F\"\r\n    }, {\r\n        \"Name\": \"PGR CN/JP/TW\",\r\n        \"Key\": \"7935585076714C4F" +
            "72436F6B57524961\"\r\n    }, {\r\n        \"Name\": \"Archeland/Kalpa of Universe\",\r\n   " +
            "     \"Key\": \"426C61636B4A61636B50726F6A656374\"\r\n    }, {\r\n        \"Name\": \"Arche" +
            "land 1.1.14\",\r\n        \"Key\": \"50726F6A65637441726368654C616E64\"\r\n    }, {\r\n    " +
            "    \"Name\": \"Neural Cloud\",\r\n        \"Key\": \"31636162383436663532393031633965\"\r\n" +
            "    }, {\r\n        \"Name\": \"Higan: Eruthyll\",\r\n        \"Key\": \"45317832633361346C" +
            "35693662377572\"\r\n    }, {\r\n        \"Name\": \"White Chord\",\r\n        \"Key\": \"79756" +
            "C6F6E6731383638676E6F6C7579\"\r\n    }, {\r\n        \"Name\": \"Mecharashi\",\r\n        \"" +
            "Key\": \"33384338334631333245374637413041\"\r\n    }, {\r\n        \"Name\": \"Castlevania" +
            ": Moon Night Fantasy\",\r\n        \"Key\": \"31323334353637383132333435363738\"\r\n    }" +
            ", {\r\n        \"Name\": \"Huā Yì Shān Xīn Zhī Yuè\",\r\n        \"Key\": \"494E484A6E68647" +
            "970716B3534377864\"\r\n    }, {\r\n        \"Name\": \"Doula Continent\",\r\n        \"Key\":" +
            " \"52346366773339474644326661785756\"\r\n    }, {\r\n        \"Name\": \"Bless Global\",\r\n" +
            "        \"Key\": \"6C6F6E67747567616D652E796A66623F\"\r\n    }, {\r\n        \"Name\": \"St" +
            "arside\",\r\n        \"Key\": \"41394A3542384D4A50554D3539464B57\"\r\n    }, {\r\n        \"" +
            "Name\": \"Resonance Soltice\",\r\n        \"Key\": \"5265736F6E616E63655265626F726E52\"\r\n" +
            "    }, {\r\n        \"Name\": \"Oblivion Override\",\r\n        \"Key\": \"7179666D6F6F6E32" +
            "3331323433343532\"\r\n    }, {\r\n        \"Name\": \"Dawnlands\",\r\n        \"Key\": \"636F6" +
            "465737339353237636F64657373\"\r\n    }, {\r\n        \"Name\": \"BB\",\r\n        \"Key\": \"5" +
            "F6C4E3F3A3F233F3F3F3F663F1A3F3F\"\r\n    }, {\r\n        \"Name\": \"Dynasty Legends 2\"," +
            "\r\n        \"Key\": \"746169686567616D6573323032323032\"\r\n    }, {\r\n        \"Name\": \"" +
            "Evernight CN\",\r\n        \"Key\": \"68687878747478736868787874747873\"\r\n    }, {\r\n   " +
            "     \"Name\": \"Xintianlong Babu\",\r\n        \"Key\": \"613235626231333463633264643332" +
            "65\"\r\n    }, {\r\n        \"Name\": \"Frostpunk: Beyond the Ice\",\r\n        \"Key\": \"736" +
            "8756978696E673838383838383838\"\r\n    }\r\n]")]
        public string keys {
            get {
                return ((string)(this["keys"]));
            }
            set {
                this["keys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<ArrayOfBoolean xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
	<boolean>true</boolean>
	<boolean>true</boolean>
	<boolean>false</boolean>
	<boolean>false</boolean>
	<boolean>false</boolean>
	<boolean>false</boolean>
	<boolean>false</boolean>
	<boolean>false</boolean>
</ArrayOfBoolean>")]
        public bool[] uvExport {
            get {
                return ((bool[])(this["uvExport"]));
            }
            set {
                this["uvExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{}")]
        public string texs {
            get {
                return ((string)(this["texs"]));
            }
            set {
                this["texs"] = value;
            }
        }
    }
}
